[package]
name = "fourier"
version = "0.1.0"
edition = "2021"

[dependencies]
fft_lib = { path = "fft_lib" }
<<<<<<< HEAD
audio_lib = { path = "audio_lib" }
=======
piston_window = "0.132.0"
>>>>>>> graphing
